"""Add agent_tool_bindings table

Revision ID: ecf5d6e61abc
Revises: 003
Create Date: 2025-12-28 17:19:26.579768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ecf5d6e61abc'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_tool_bindings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_tool_bindings_agent_tool', 'agent_tool_bindings', ['agent_id', 'tool_id'], unique=True)
    op.create_index(op.f('ix_agent_tool_bindings_agent_id'), 'agent_tool_bindings', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_tool_bindings_agent_id'), table_name='agent_tool_bindings')
    op.drop_index('idx_agent_tool_bindings_agent_tool', table_name='agent_tool_bindings')
    op.drop_table('agent_tool_bindings')
    # ### end Alembic commands ###
