"""Pydantic schemas for request/response."""

from aiops_tools.schemas.llm import (
    LLMTool,
    LLMToolFunction,
    LLMToolListResponse,
    LLMToolParameter,
    ToolInvokeRequest,
    ToolInvokeResponse,
    transform_to_llm_format,
)
from aiops_tools.schemas.tool import (
    CategoryDeleteRequest,
    CategoryGetRequest,
    CategoryListRequest,
    CategoryListResponse,
    CategoryPaginatedData,
    CategoryUpdateRequest,
    ExecutionCancelRequest,
    PaginationRequest,
    ToolCategoryCreate,
    ToolCategoryResponse,
    ToolCategoryUpdate,
    ToolCreate,
    ToolDeleteRequest,
    ToolExecutionRequest,
    ToolExecutionResponse,
    ToolGetRequest,
    ToolListRequest,
    ToolListResponse,
    ToolPaginatedData,
    ToolResponse,
    ToolUpdate,
    ToolUpdateRequest,
)

__all__ = [
    # Pagination schemas (Constitution Principle V & VI)
    "PaginationRequest",
    "CategoryPaginatedData",
    "CategoryListRequest",
    "CategoryListResponse",
    "ToolPaginatedData",
    "ToolListRequest",
    "ToolListResponse",
    # Category schemas
    "ToolCategoryCreate",
    "ToolCategoryResponse",
    "ToolCategoryUpdate",
    "CategoryGetRequest",
    "CategoryDeleteRequest",
    "CategoryUpdateRequest",
    # Tool schemas
    "ToolCreate",
    "ToolExecutionRequest",
    "ToolExecutionResponse",
    "ToolResponse",
    "ToolUpdate",
    "ToolGetRequest",
    "ToolDeleteRequest",
    "ToolUpdateRequest",
    "ExecutionCancelRequest",
    # LLM schemas
    "LLMTool",
    "LLMToolFunction",
    "LLMToolListResponse",
    "LLMToolParameter",
    "ToolInvokeRequest",
    "ToolInvokeResponse",
    "transform_to_llm_format",
]
